<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS3gxSZ0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS3gxSZ0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS3gxSZ0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS3gxSZ0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerS3gxSZ0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'S3gxSZ0',
    'container.build_id' => '116baf0f',
    'container.build_time' => 1578221474,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS3gxSZ0');
